//! Registered ordinary YR command metadata, in original 532150 registration order.
//! Source: tools/storage_oracle/keyboard_bindings.py executes original registration;
//! each CSF key is read from the registered object getter, not inferred from its name.

use super::HotkeyCommand;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct CommandMetadata {
    pub command: HotkeyCommand,
    pub ini_name: &'static str,
    pub name_key: &'static str,
    pub category_key: &'static str,
    pub description_key: &'static str,
    /// Original object +4 argument for the team/taunt localized printf format.
    pub parameter: Option<u8>,
}

macro_rules! command {
    ($command:expr, $ini:literal, $name:literal, $category:literal, $description:literal, $parameter:expr) => {
        CommandMetadata {
            command: $command,
            ini_name: $ini,
            name_key: $name,
            category_key: $category,
            description_key: $description,
            parameter: $parameter,
        }
    };
}

pub(crate) fn registered_commands() -> &'static [CommandMetadata] {
    &REGISTERED_COMMANDS
}

const REGISTERED_COMMANDS: [CommandMetadata; 87] = [
    command!(
        HotkeyCommand::Follow,
        "Follow",
        "TXT_FOLLOW",
        "TXT_INTERFACE",
        "TXT_FOLLOW_DESC",
        None
    ),
    command!(
        HotkeyCommand::View(0),
        "View1",
        "TXT_VIEW_BOOKMARK1",
        "TXT_INTERFACE",
        "TXT_VIEW_BOOKMARK1_DESC",
        None
    ),
    command!(
        HotkeyCommand::View(1),
        "View2",
        "TXT_VIEW_BOOKMARK2",
        "TXT_INTERFACE",
        "TXT_VIEW_BOOKMARK2_DESC",
        None
    ),
    command!(
        HotkeyCommand::View(2),
        "View3",
        "TXT_VIEW_BOOKMARK3",
        "TXT_INTERFACE",
        "TXT_VIEW_BOOKMARK3_DESC",
        None
    ),
    command!(
        HotkeyCommand::View(3),
        "View4",
        "TXT_VIEW_BOOKMARK4",
        "TXT_INTERFACE",
        "TXT_VIEW_BOOKMARK4_DESC",
        None
    ),
    command!(
        HotkeyCommand::SetView(0),
        "SetView1",
        "TXT_SET_BOOKMARK1",
        "TXT_INTERFACE",
        "TXT_SET_BOOKMARK1_DESC",
        None
    ),
    command!(
        HotkeyCommand::SetView(1),
        "SetView2",
        "TXT_SET_BOOKMARK2",
        "TXT_INTERFACE",
        "TXT_SET_BOOKMARK2_DESC",
        None
    ),
    command!(
        HotkeyCommand::SetView(2),
        "SetView3",
        "TXT_SET_BOOKMARK3",
        "TXT_INTERFACE",
        "TXT_SET_BOOKMARK3_DESC",
        None
    ),
    command!(
        HotkeyCommand::SetView(3),
        "SetView4",
        "TXT_SET_BOOKMARK4",
        "TXT_INTERFACE",
        "TXT_SET_BOOKMARK4_DESC",
        None
    ),
    command!(
        HotkeyCommand::Options,
        "Options",
        "TXT_OPTIONS",
        "TXT_INTERFACE",
        "TXT_OPTIONS_DESC",
        None
    ),
    command!(
        HotkeyCommand::SidebarUp,
        "SidebarUp",
        "TXT_SIDEBAR_UP",
        "TXT_INTERFACE",
        "TXT_SIDEBAR_UP_DESC",
        None
    ),
    command!(
        HotkeyCommand::SidebarDown,
        "SidebarDown",
        "TXT_SIDEBAR_DOWN",
        "TXT_INTERFACE",
        "TXT_SIDEBAR_DOWN_DESC",
        None
    ),
    command!(
        HotkeyCommand::CenterOnRadarEvent,
        "CenterOnRadarEvent",
        "TXT_RADAR_EVENT",
        "TXT_INTERFACE",
        "TXT_RADAR_EVENT_DESC",
        None
    ),
    command!(
        HotkeyCommand::PlaceBeacon,
        "PlaceBeacon",
        "TXT_PLACE_BEACON",
        "TXT_INTERFACE",
        "TXT_PLACE_BEACON_DESC",
        None
    ),
    command!(
        HotkeyCommand::ToggleSell,
        "ToggleSell",
        "TXT_SELL_MODE",
        "TXT_INTERFACE",
        "TXT_SELL_MODE_DESC",
        None
    ),
    command!(
        HotkeyCommand::ToggleRepair,
        "ToggleRepair",
        "TXT_REPAIR_MODE",
        "TXT_INTERFACE",
        "TXT_REPAIR_MODE_DESC",
        None
    ),
    command!(
        HotkeyCommand::ToggleAlliance,
        "ToggleAlliance",
        "TXT_ALLIANCE",
        "TXT_CONTROL",
        "TXT_ALLIANCE_DESC",
        None
    ),
    command!(
        HotkeyCommand::CenterBase,
        "CenterBase",
        "TXT_CENTER_BASE",
        "TXT_SELECTION",
        "TXT_CENTER_BASE_DESC",
        None
    ),
    command!(
        HotkeyCommand::CenterView,
        "CenterView",
        "TXT_CENTER_VIEW",
        "TXT_SELECTION",
        "TXT_CENTER_VIEW_DESC",
        None
    ),
    command!(
        HotkeyCommand::ScatterObject,
        "ScatterObject",
        "TXT_SCATTER",
        "TXT_CONTROL",
        "TXT_SCATTER_DESC",
        None
    ),
    command!(
        HotkeyCommand::GuardObject,
        "GuardObject",
        "TXT_GUARD",
        "TXT_CONTROL",
        "TXT_GUARD_DESC",
        None
    ),
    command!(
        HotkeyCommand::StopObject,
        "StopObject",
        "TXT_STOP_OBJECT",
        "TXT_CONTROL",
        "TXT_STOP_OBJECT_DESC",
        None
    ),
    command!(
        HotkeyCommand::AllToCheer,
        "AllToCheer",
        "Cmnd:AllCheer",
        "TXT_CONTROL",
        "Cmnd:AllCheerDesc",
        None
    ),
    command!(
        HotkeyCommand::DeployObject,
        "DeployObject",
        "TXT_DEPLOY_OBJECT",
        "TXT_CONTROL",
        "TXT_DEPLOY_OBJECT_DESC",
        None
    ),
    command!(
        HotkeyCommand::PreviousObject,
        "PreviousObject",
        "TXT_PREV_OBJECT",
        "TXT_SELECTION",
        "TXT_PREV_OBJECT_DESC",
        None
    ),
    command!(
        HotkeyCommand::NextObject,
        "NextObject",
        "TXT_NEXT_OBJECT",
        "TXT_SELECTION",
        "TXT_NEXT_OBJECT_DESC",
        None
    ),
    command!(
        HotkeyCommand::PlanningMode,
        "PlanningMode",
        "Cmnd:PlanningMode",
        "TXT_CONTROL",
        "Cmnd:PlanningModeDesc",
        None
    ),
    command!(
        HotkeyCommand::CombatantSelect,
        "CombatantSelect",
        "Cmnd:CombatantSelect",
        "TXT_SELECTION",
        "Cmnd:CombatantSelectDesc",
        None
    ),
    command!(
        HotkeyCommand::TypeSelect,
        "TypeSelect",
        "Cmnd:TypeSelect",
        "TXT_SELECTION",
        "Cmnd:TypeSelectDesc",
        None
    ),
    command!(
        HotkeyCommand::HealthNav,
        "HealthNav",
        "Cmnd:HealthNavigation",
        "TXT_SELECTION",
        "Cmnd:HealthNavigationDesc",
        None
    ),
    command!(
        HotkeyCommand::VeterancyNav,
        "VeterancyNav",
        "Cmnd:VetNavigation",
        "TXT_SELECTION",
        "Cmnd:VetNavigationDesc",
        None
    ),
    command!(
        HotkeyCommand::StructureTab,
        "StructureTab",
        "TXT_STRUCTURE_TAB",
        "TXT_INTERFACE",
        "TXT_STRUCTURE_TAB_DESC",
        None
    ),
    command!(
        HotkeyCommand::DefenseTab,
        "DefenseTab",
        "TXT_DEFENSE_TAB",
        "TXT_INTERFACE",
        "TXT_DEFENSE_TAB_DESC",
        None
    ),
    command!(
        HotkeyCommand::UnitTab,
        "UnitTab",
        "TXT_UNIT_TAB",
        "TXT_INTERFACE",
        "TXT_UNIT_TAB_DESC",
        None
    ),
    command!(
        HotkeyCommand::InfantryTab,
        "InfantryTab",
        "TXT_INFANTRY_TAB",
        "TXT_INTERFACE",
        "TXT_INFANTRY_TAB_DESC",
        None
    ),
    command!(
        HotkeyCommand::TeamCreate(1),
        "TeamCreate_1",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(1)
    ),
    command!(
        HotkeyCommand::TeamCreate(2),
        "TeamCreate_2",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(2)
    ),
    command!(
        HotkeyCommand::TeamCreate(3),
        "TeamCreate_3",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(3)
    ),
    command!(
        HotkeyCommand::TeamCreate(4),
        "TeamCreate_4",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(4)
    ),
    command!(
        HotkeyCommand::TeamCreate(5),
        "TeamCreate_5",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(5)
    ),
    command!(
        HotkeyCommand::TeamCreate(6),
        "TeamCreate_6",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(6)
    ),
    command!(
        HotkeyCommand::TeamCreate(7),
        "TeamCreate_7",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(7)
    ),
    command!(
        HotkeyCommand::TeamCreate(8),
        "TeamCreate_8",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(8)
    ),
    command!(
        HotkeyCommand::TeamCreate(9),
        "TeamCreate_9",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(9)
    ),
    command!(
        HotkeyCommand::TeamCreate(0),
        "TeamCreate_10",
        "TXT_CREATE_TEAM",
        "TXT_TEAM",
        "TXT_CREATE_TEAM_DESC",
        Some(10)
    ),
    command!(
        HotkeyCommand::TeamSelect(1),
        "TeamSelect_1",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(1)
    ),
    command!(
        HotkeyCommand::TeamSelect(2),
        "TeamSelect_2",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(2)
    ),
    command!(
        HotkeyCommand::TeamSelect(3),
        "TeamSelect_3",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(3)
    ),
    command!(
        HotkeyCommand::TeamSelect(4),
        "TeamSelect_4",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(4)
    ),
    command!(
        HotkeyCommand::TeamSelect(5),
        "TeamSelect_5",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(5)
    ),
    command!(
        HotkeyCommand::TeamSelect(6),
        "TeamSelect_6",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(6)
    ),
    command!(
        HotkeyCommand::TeamSelect(7),
        "TeamSelect_7",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(7)
    ),
    command!(
        HotkeyCommand::TeamSelect(8),
        "TeamSelect_8",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(8)
    ),
    command!(
        HotkeyCommand::TeamSelect(9),
        "TeamSelect_9",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(9)
    ),
    command!(
        HotkeyCommand::TeamSelect(0),
        "TeamSelect_10",
        "TXT_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_SELECT_TEAM_DESC",
        Some(10)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(1),
        "TeamAddSelect_1",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(1)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(2),
        "TeamAddSelect_2",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(2)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(3),
        "TeamAddSelect_3",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(3)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(4),
        "TeamAddSelect_4",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(4)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(5),
        "TeamAddSelect_5",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(5)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(6),
        "TeamAddSelect_6",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(6)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(7),
        "TeamAddSelect_7",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(7)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(8),
        "TeamAddSelect_8",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(8)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(9),
        "TeamAddSelect_9",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(9)
    ),
    command!(
        HotkeyCommand::TeamAddSelect(0),
        "TeamAddSelect_10",
        "TXT_ADD_SELECT_TEAM",
        "TXT_TEAM",
        "TXT_ADD_SELECT_TEAM_DESC",
        Some(10)
    ),
    command!(
        HotkeyCommand::TeamCenter(1),
        "TeamCenter_1",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(1)
    ),
    command!(
        HotkeyCommand::TeamCenter(2),
        "TeamCenter_2",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(2)
    ),
    command!(
        HotkeyCommand::TeamCenter(3),
        "TeamCenter_3",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(3)
    ),
    command!(
        HotkeyCommand::TeamCenter(4),
        "TeamCenter_4",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(4)
    ),
    command!(
        HotkeyCommand::TeamCenter(5),
        "TeamCenter_5",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(5)
    ),
    command!(
        HotkeyCommand::TeamCenter(6),
        "TeamCenter_6",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(6)
    ),
    command!(
        HotkeyCommand::TeamCenter(7),
        "TeamCenter_7",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(7)
    ),
    command!(
        HotkeyCommand::TeamCenter(8),
        "TeamCenter_8",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(8)
    ),
    command!(
        HotkeyCommand::TeamCenter(9),
        "TeamCenter_9",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(9)
    ),
    command!(
        HotkeyCommand::TeamCenter(0),
        "TeamCenter_10",
        "TXT_CENTER_TEAM",
        "TXT_TEAM",
        "TXT_CENTER_TEAM_DESC",
        Some(10)
    ),
    command!(
        HotkeyCommand::Taunt(0),
        "Taunt_1",
        "TXT_TAUNT_NUMBER",
        "TXT_TAUNT",
        "TXT_TAUNT_DESC",
        Some(1)
    ),
    command!(
        HotkeyCommand::Taunt(1),
        "Taunt_2",
        "TXT_TAUNT_NUMBER",
        "TXT_TAUNT",
        "TXT_TAUNT_DESC",
        Some(2)
    ),
    command!(
        HotkeyCommand::Taunt(2),
        "Taunt_3",
        "TXT_TAUNT_NUMBER",
        "TXT_TAUNT",
        "TXT_TAUNT_DESC",
        Some(3)
    ),
    command!(
        HotkeyCommand::Taunt(3),
        "Taunt_4",
        "TXT_TAUNT_NUMBER",
        "TXT_TAUNT",
        "TXT_TAUNT_DESC",
        Some(4)
    ),
    command!(
        HotkeyCommand::Taunt(4),
        "Taunt_5",
        "TXT_TAUNT_NUMBER",
        "TXT_TAUNT",
        "TXT_TAUNT_DESC",
        Some(5)
    ),
    command!(
        HotkeyCommand::Taunt(5),
        "Taunt_6",
        "TXT_TAUNT_NUMBER",
        "TXT_TAUNT",
        "TXT_TAUNT_DESC",
        Some(6)
    ),
    command!(
        HotkeyCommand::Taunt(6),
        "Taunt_7",
        "TXT_TAUNT_NUMBER",
        "TXT_TAUNT",
        "TXT_TAUNT_DESC",
        Some(7)
    ),
    command!(
        HotkeyCommand::Taunt(7),
        "Taunt_8",
        "TXT_TAUNT_NUMBER",
        "TXT_TAUNT",
        "TXT_TAUNT_DESC",
        Some(8)
    ),
    command!(
        HotkeyCommand::ScreenCapture,
        "ScreenCapture",
        "TXT_SCRNCAP",
        "TXT_INTERFACE",
        "TXT_SCRNCAP_DESC",
        None
    ),
    command!(
        HotkeyCommand::PageUser,
        "PageUser",
        "TXT_PAGEUSER",
        "TXT_INTERFACE",
        "TXT_PAGEUSER_DESC",
        None
    ),
    command!(
        HotkeyCommand::CursorCheat,
        "CursorCheat",
        "GUI:CursorCheat",
        "GUI:Debug",
        "DESC:CursorCheat",
        None
    ),
    command!(
        HotkeyCommand::Delete,
        "Delete",
        "Cmnd:Delete",
        "TXT_INTERFACE",
        "Cmnd:DeleteDesc",
        None
    ),
];
