param(
    [Parameter(Mandatory = $true)]
    [string]$GamemdPath,
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

# gamemd.exe image base is 0x00400000. The .data section has matching RVA and
# raw-file offsets, so the native Math__atan2 table at VA 0x008610B4 begins at
# file offset 0x004610B4.
$tableOffset = 0x004610B4
$entryCount = 4097
$headCount = 65

$bytes = [IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $GamemdPath))
$tableBytes = $entryCount * 4
if ($bytes.Length -lt $tableOffset + $tableBytes) {
    throw "gamemd.exe is too short for the native atan table"
}

$values = [uint32[]]::new($entryCount)
for ($i = 0; $i -lt $entryCount; $i++) {
    $values[$i] = [BitConverter]::ToUInt32($bytes, $tableOffset + $i * 4)
}
if ($values[0] -ne 0x00000000 -or $values[1] -ne 0x3CC7F458 -or $values[4096] -ne 0x3FC7C820) {
    throw "native atan table sentinels do not match active retail gamemd.exe"
}

$deltas = [uint16[]]::new($entryCount - $headCount)
for ($i = $headCount; $i -lt $entryCount; $i++) {
    $delta = [uint64]$values[$i] - [uint64]$values[$i - 1]
    if ($delta -gt [uint16]::MaxValue) {
        throw "atan table delta at index $i does not fit u16: $delta"
    }
    $deltas[$i - $headCount] = [uint16]$delta
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('//! Machine-derived active-retail arctangent table.')
$lines.Add('//!')
$lines.Add('//! Generated by `tools/generate_native_atan_table.ps1`. The first 65 values')
$lines.Add('//! are absolute IEEE-754 `f32` bits; the monotone tail is stored as exact')
$lines.Add('//! `u16` bit-pattern deltas to keep the checked-in data compact.')
$lines.Add('')
$lines.Add("pub(super) const ATAN_HEAD: [u32; $headCount] = [")
for ($i = 0; $i -lt $headCount; $i += 8) {
    $end = [Math]::Min($i + 8, $headCount)
    $row = for ($j = $i; $j -lt $end; $j++) { '0x{0:X8}' -f $values[$j] }
    $lines.Add('    ' + ($row -join ', ') + ',')
}
$lines.Add('];')
$lines.Add('')
$lines.Add("pub(super) const ATAN_TAIL_DELTAS: [u16; $($deltas.Length)] = [")
for ($i = 0; $i -lt $deltas.Length; $i += 16) {
    $end = [Math]::Min($i + 16, $deltas.Length)
    $row = for ($j = $i; $j -lt $end; $j++) { '0x{0:X4}' -f $deltas[$j] }
    $lines.Add('    ' + ($row -join ', ') + ',')
}
$lines.Add('];')
$lines.Add('')

$resolvedOutput = [IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputPath))
$outputDirectory = [IO.Path]::GetDirectoryName($resolvedOutput)
[IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[IO.File]::WriteAllText(
    $resolvedOutput,
    ($lines -join [Environment]::NewLine),
    [Text.UTF8Encoding]::new($false)
)
